### PR TITLE
add methods from interfaces of components to template parser

### PR DESCRIPTION
**Pull request by thelsing**
This way one can implement things like i18n with default methods in interfaces.

### CODE REVIEW

**Comment by adrienbaron** [comment]
Happy new year! And thank you for the PR! Could you try and add an test for this in the test Maven module?
This would help us make sure this works at runtime when GWT compiles the code to JS 😊.

You can see CONTRIBUTING.md for details about the tests and how to run them 👍

**Comment by thelsing** [comment]
I added a method to test generation of calls to default methods of interfaces.

**Comment by thelsing** [comment]
I used JDK11 because on JDK17 some test fail on JDK17 and 16

**Comment by adrienbaron** [comment]
I had a look at your test and that's not really what I had in mind 😅, those tests are more "unit" level and don't ensure the code actually works at runtime in a browser once GWT converted to JS.

I took the liberty of writting something closer to what I had in mind 👍 .
I pushed it on your branch by mistake instead of a branch on my repo xD, I hope thats OK, tell me if you're happy for me to merge 👍

**Comment by thelsing** [comment]
It's good that you added the test. I'm afraid it would have taken much more time for me. 
For me it's fine to merge it.

**Pull request merged**
